/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AddUsernameRouteImport } from './routes/add.$username'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicHooksGoogleCalendarCallbackRouteImport } from './routes/api/public/hooks/google-calendar-callback'
import { Route as ApiPublicHooksOutlookCalendarCallbackRouteImport } from './routes/api/public/hooks/outlook-calendar-callback'
import { Route as ApiPublicHooksProcessScanJobsRouteImport } from './routes/api/public/hooks/process-scan-jobs'
import { Route as ApiPublicHooksRecheckPlanWeatherRouteImport } from './routes/api/public/hooks/recheck-plan-weather'
import { Route as ApiPublicHooksSendMorningLooksRouteImport } from './routes/api/public/hooks/send-morning-looks'
import { Route as ApiPublicHooksSyncCalendarsRouteImport } from './routes/api/public/hooks/sync-calendars'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AddUsernameRoute = AddUsernameRouteImport.update({
  id: '/add/$username',
  path: '/add/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGoogleCalendarCallbackRoute =
  ApiPublicHooksGoogleCalendarCallbackRouteImport.update({
    id: '/api/public/hooks/google-calendar-callback',
    path: '/api/public/hooks/google-calendar-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOutlookCalendarCallbackRoute =
  ApiPublicHooksOutlookCalendarCallbackRouteImport.update({
    id: '/api/public/hooks/outlook-calendar-callback',
    path: '/api/public/hooks/outlook-calendar-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessScanJobsRoute =
  ApiPublicHooksProcessScanJobsRouteImport.update({
    id: '/api/public/hooks/process-scan-jobs',
    path: '/api/public/hooks/process-scan-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecheckPlanWeatherRoute =
  ApiPublicHooksRecheckPlanWeatherRouteImport.update({
    id: '/api/public/hooks/recheck-plan-weather',
    path: '/api/public/hooks/recheck-plan-weather',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendMorningLooksRoute =
  ApiPublicHooksSendMorningLooksRouteImport.update({
    id: '/api/public/hooks/send-morning-looks',
    path: '/api/public/hooks/send-morning-looks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncCalendarsRoute =
  ApiPublicHooksSyncCalendarsRouteImport.update({
    id: '/api/public/hooks/sync-calendars',
    path: '/api/public/hooks/sync-calendars',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/add/$username': typeof AddUsernameRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/google-calendar-callback': typeof ApiPublicHooksGoogleCalendarCallbackRoute
  '/api/public/hooks/outlook-calendar-callback': typeof ApiPublicHooksOutlookCalendarCallbackRoute
  '/api/public/hooks/process-scan-jobs': typeof ApiPublicHooksProcessScanJobsRoute
  '/api/public/hooks/recheck-plan-weather': typeof ApiPublicHooksRecheckPlanWeatherRoute
  '/api/public/hooks/send-morning-looks': typeof ApiPublicHooksSendMorningLooksRoute
  '/api/public/hooks/sync-calendars': typeof ApiPublicHooksSyncCalendarsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/add/$username': typeof AddUsernameRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/google-calendar-callback': typeof ApiPublicHooksGoogleCalendarCallbackRoute
  '/api/public/hooks/outlook-calendar-callback': typeof ApiPublicHooksOutlookCalendarCallbackRoute
  '/api/public/hooks/process-scan-jobs': typeof ApiPublicHooksProcessScanJobsRoute
  '/api/public/hooks/recheck-plan-weather': typeof ApiPublicHooksRecheckPlanWeatherRoute
  '/api/public/hooks/send-morning-looks': typeof ApiPublicHooksSendMorningLooksRoute
  '/api/public/hooks/sync-calendars': typeof ApiPublicHooksSyncCalendarsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/add/$username': typeof AddUsernameRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/google-calendar-callback': typeof ApiPublicHooksGoogleCalendarCallbackRoute
  '/api/public/hooks/outlook-calendar-callback': typeof ApiPublicHooksOutlookCalendarCallbackRoute
  '/api/public/hooks/process-scan-jobs': typeof ApiPublicHooksProcessScanJobsRoute
  '/api/public/hooks/recheck-plan-weather': typeof ApiPublicHooksRecheckPlanWeatherRoute
  '/api/public/hooks/send-morning-looks': typeof ApiPublicHooksSendMorningLooksRoute
  '/api/public/hooks/sync-calendars': typeof ApiPublicHooksSyncCalendarsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/add/$username'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/google-calendar-callback'
    | '/api/public/hooks/outlook-calendar-callback'
    | '/api/public/hooks/process-scan-jobs'
    | '/api/public/hooks/recheck-plan-weather'
    | '/api/public/hooks/send-morning-looks'
    | '/api/public/hooks/sync-calendars'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/add/$username'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/google-calendar-callback'
    | '/api/public/hooks/outlook-calendar-callback'
    | '/api/public/hooks/process-scan-jobs'
    | '/api/public/hooks/recheck-plan-weather'
    | '/api/public/hooks/send-morning-looks'
    | '/api/public/hooks/sync-calendars'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/add/$username'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/google-calendar-callback'
    | '/api/public/hooks/outlook-calendar-callback'
    | '/api/public/hooks/process-scan-jobs'
    | '/api/public/hooks/recheck-plan-weather'
    | '/api/public/hooks/send-morning-looks'
    | '/api/public/hooks/sync-calendars'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AddUsernameRoute: typeof AddUsernameRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksGoogleCalendarCallbackRoute: typeof ApiPublicHooksGoogleCalendarCallbackRoute
  ApiPublicHooksOutlookCalendarCallbackRoute: typeof ApiPublicHooksOutlookCalendarCallbackRoute
  ApiPublicHooksProcessScanJobsRoute: typeof ApiPublicHooksProcessScanJobsRoute
  ApiPublicHooksRecheckPlanWeatherRoute: typeof ApiPublicHooksRecheckPlanWeatherRoute
  ApiPublicHooksSendMorningLooksRoute: typeof ApiPublicHooksSendMorningLooksRoute
  ApiPublicHooksSyncCalendarsRoute: typeof ApiPublicHooksSyncCalendarsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/$username': {
      id: '/add/$username'
      path: '/add/$username'
      fullPath: '/add/$username'
      preLoaderRoute: typeof AddUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/google-calendar-callback': {
      id: '/api/public/hooks/google-calendar-callback'
      path: '/api/public/hooks/google-calendar-callback'
      fullPath: '/api/public/hooks/google-calendar-callback'
      preLoaderRoute: typeof ApiPublicHooksGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/outlook-calendar-callback': {
      id: '/api/public/hooks/outlook-calendar-callback'
      path: '/api/public/hooks/outlook-calendar-callback'
      fullPath: '/api/public/hooks/outlook-calendar-callback'
      preLoaderRoute: typeof ApiPublicHooksOutlookCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-scan-jobs': {
      id: '/api/public/hooks/process-scan-jobs'
      path: '/api/public/hooks/process-scan-jobs'
      fullPath: '/api/public/hooks/process-scan-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessScanJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recheck-plan-weather': {
      id: '/api/public/hooks/recheck-plan-weather'
      path: '/api/public/hooks/recheck-plan-weather'
      fullPath: '/api/public/hooks/recheck-plan-weather'
      preLoaderRoute: typeof ApiPublicHooksRecheckPlanWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-morning-looks': {
      id: '/api/public/hooks/send-morning-looks'
      path: '/api/public/hooks/send-morning-looks'
      fullPath: '/api/public/hooks/send-morning-looks'
      preLoaderRoute: typeof ApiPublicHooksSendMorningLooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-calendars': {
      id: '/api/public/hooks/sync-calendars'
      path: '/api/public/hooks/sync-calendars'
      fullPath: '/api/public/hooks/sync-calendars'
      preLoaderRoute: typeof ApiPublicHooksSyncCalendarsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AddUsernameRoute: AddUsernameRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksGoogleCalendarCallbackRoute:
    ApiPublicHooksGoogleCalendarCallbackRoute,
  ApiPublicHooksOutlookCalendarCallbackRoute:
    ApiPublicHooksOutlookCalendarCallbackRoute,
  ApiPublicHooksProcessScanJobsRoute: ApiPublicHooksProcessScanJobsRoute,
  ApiPublicHooksRecheckPlanWeatherRoute: ApiPublicHooksRecheckPlanWeatherRoute,
  ApiPublicHooksSendMorningLooksRoute: ApiPublicHooksSendMorningLooksRoute,
  ApiPublicHooksSyncCalendarsRoute: ApiPublicHooksSyncCalendarsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
